apiVersion: duragent/v1alpha1
kind: Agent
metadata:
  name: {name}
  # description: A helpful assistant
  # version: 0.1.0
  # labels:
  #   domain: general
spec:
  model:
    provider: {provider}
    name: {model}
    # temperature: 0.7
    # max_output_tokens: 4096
    # max_input_tokens: 200000
    # base_url: https://custom-endpoint.example.com

  # Agent personality (who the agent IS) - path to a markdown file
  soul: ./SOUL.md

  # System prompt (what the agent DOES) - path to a markdown file
  system_prompt: ./SYSTEM_PROMPT.md

  # Additional runtime instructions - path to a markdown file
  # instructions: ./INSTRUCTIONS.md

  session:
    on_disconnect: pause         # pause | continue
    # ttl_hours: 168             # per-agent override (0 to disable)
    # compaction: discard        # per-agent override: discard | archive | disabled
    # max_tool_iterations: 10
    # context:
    #   max_history_tokens: 20000
    #   max_tool_result_tokens: 8000
    #   tool_result_truncation: head   # head | tail | both
    #   tool_result_keep_first: 2
    #   tool_result_keep_last: 5

  # Persistent memory
  # memory:
  #   backend: filesystem

  # Access control (for gateway integrations)
  # access:
  #   dm:
  #     policy: open             # open | disabled | allowlist
  #     allowlist: []
  #   groups:
  #     policy: open             # open | disabled | allowlist
  #     allowlist: []
  #     activation: mention      # mention | always
  #     sender_default: allow    # allow | passive | silent | block
  #     context_buffer:
  #       mode: silent           # silent | passive
  #       max_messages: 100
  #       max_age_hours: 24
  #     queue:
  #       mode: batch            # batch | sequential | drop
  #       max_pending: 10
  #       overflow: drop_old     # drop_old | drop_new | reject
  #       debounce:
  #         enabled: true
  #         window_ms: 1500

  # Tool lifecycle hooks (guards & steering)
  # hooks:
  #   before_tool:
  #     - match: "background_process:send_keys"
  #       type: depends_on
  #       prior: "background_process:capture"
  #       match_arg: handle
  #     - match: "memory:recall"
  #       type: skip_duplicate
  #       match_args: [days]
  #   after_tool:
  #     - match: "background_process:capture"
  #       message: "Base your next action on the captured screen output above."
  #     - match: "background_process:spawn"
  #       message: "Remember to start a watcher for this process if needed."
  #       unless:
  #         wait: true

  # Tools
  # tools:
  #   - type: builtin
  #     name: bash
  #   - type: builtin
  #     name: web
  #   - type: builtin
  #     name: schedule
  #   - type: builtin
  #     name: background_process
  #   - type: builtin
  #     name: session
  #   - type: builtin
  #     name: reload_tools
  #   - type: cli
  #     name: my-tool
  #     command: ./tools/my-tool.sh
  #     description: Runs my custom tool
